const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.wrap,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Plugins.sliderbar,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Plugins.Audio,
		C3.Plugins.progressbar,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Share,
		C3.Plugins.advert,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Share.Cnds.IsSupported,
		C3.Plugins.Share.Acts.Share,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.advert.Cnds.OnBannerFailedToLoad,
		C3.Plugins.advert.Acts.ShowBanner,
		C3.Plugins.advert.Cnds.IsShowingBanner,
		C3.Plugins.advert.Cnds.IsBannerLoaded,
		C3.Plugins.advert.Cnds.OnBannerReady,
		C3.Plugins.System.Acts.LoadLayoutTextures,
		C3.Plugins.System.Cnds.IsLoadingImages,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.System.Cnds.OnImageLoadingComplete,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.advert.Acts.HideBanner,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.advert.Cnds.OnRewardedFailedToLoad,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Cnds.OnChanged,
		C3.Plugins.sliderbar.Cnds.OnClicked,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.advert.Cnds.IsRewardedLoaded,
		C3.Plugins.advert.Acts.ShowRewarded,
		C3.Plugins.advert.Cnds.OnRewardedComplete
	];
};
self.C3_JsPropNameTable = [
	{bg10: 0},
	{bg12: 0},
	{bg14: 0},
	{bg2: 0},
	{bg3: 0},
	{bg4: 0},
	{bg5: 0},
	{bg7: 0},
	{bg8: 0},
	{bg9: 0},
	{BG15: 0},
	{bg1: 0},
	{ScrollTo: 0},
	{camera: 0},
	{TiledBackground2: 0},
	{BGTELA3: 0},
	{FundoEmBlocos: 0},
	{Wrap: 0},
	{Platform: 0},
	{bola: 0},
	{SOMBRA: 0},
	{Sine: 0},
	{animacaoraio: 0},
	{Jumpthru: 0},
	{grama: 0},
	{nuvem: 0},
	{nuvem_trovao: 0},
	{tijolo1: 0},
	{tijolo2: 0},
	{tijolo_colorido: 0},
	{tijolo_dourado: 0},
	{Sólido: 0},
	{TIJOLO_METAL: 0},
	{Bullet: 0},
	{ESTRELAS: 0},
	{medalha_ouro: 0},
	{medalha_bronze: 0},
	{medalha_prata: 0},
	{medalha3rngamesentretenimento: 0},
	{obstaculo1: 0},
	{obstaculo_prata: 0},
	{Particles: 0},
	{Particles10: 0},
	{Particles12: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Particles8: 0},
	{Particles7: 0},
	{particula: 0},
	{Particles9: 0},
	{Particles6: 0},
	{Particles11: 0},
	{Particles13: 0},
	{pedramarromescuro: 0},
	{predramarromclaro: 0},
	{rocha: 0},
	{Particles14: 0},
	{Particles15: 0},
	{Partículas: 0},
	{particula_tijolo_metal: 0},
	{PARTICULA_TIJOLO_COLORIDO: 0},
	{PARTICULA_TIJOLO_DOURADO: 0},
	{Particles16: 0},
	{PREMIO_3RN_GAMES: 0},
	{PREMIO_A: 0},
	{PREMIO_N: 0},
	{PREMIO_S: 0},
	{PREMIO_R: 0},
	{PREMIO_D: 0},
	{afrodite: 0},
	{pandora: 0},
	{poseidom: 0},
	{persefone: 0},
	{zeus: 0},
	{cronos: 0},
	{PREMIO_OURO: 0},
	{PREMIO_PRATA: 0},
	{PREMIO_BRONZE: 0},
	{premio3rngames: 0},
	{playstore_3rngamesentretenimento: 0},
	{TXTPULOS: 0},
	{PLANODEFUNDO: 0},
	{BTNJOGAR: 0},
	{LOGO_3RN_GAMES_ENTRETENIMENTO: 0},
	{SETA_DIREITA: 0},
	{SETA_ESQUERDA: 0},
	{SliderBar: 0},
	{BTNANUNCIOVIDEO: 0},
	{Fade: 0},
	{Sine2: 0},
	{ANIMACAO: 0},
	{btnganhoujogo: 0},
	{seta_direita_desativado: 0},
	{seta_esquerda_desativado: 0},
	{btn_continuar_desativado: 0},
	{Atrelar: 0},
	{btn_nao: 0},
	{btn_novo_jogo: 0},
	{btn_sim: 0},
	{btncontinuar: 0},
	{PAINEL_CERTEZA: 0},
	{Girar: 0},
	{PAINEL_ORBITA: 0},
	{poder_amarelo: 0},
	{poder_azul: 0},
	{poder_rosa: 0},
	{poder_roxo: 0},
	{poder_verde: 0},
	{poder_vermelho: 0},
	{Sprite: 0},
	{SETADIREITA: 0},
	{SETAESQUERDA: 0},
	{decmusic5: 0},
	{decmusic10: 0},
	{decmusic2: 0},
	{decmusic4: 0},
	{decmusic7: 0},
	{decmusic8: 0},
	{DEC_PONTOS: 0},
	{setavoltarmenu: 0},
	{texto1: 0},
	{texto2: 0},
	{texto3: 0},
	{BTN_CONTINUAR: 0},
	{BTN_MENU: 0},
	{BTN_PAUSAR: 0},
	{painel: 0},
	{S1: 0},
	{S2: 0},
	{S3: 0},
	{S4: 0},
	{S5: 0},
	{S6: 0},
	{S7: 0},
	{S8: 0},
	{Audio: 0},
	{BarraDeProgresso: 0},
	{Browser: 0},
	{Function: 0},
	{Gamepad: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Compartilhar: 0},
	{BTN_COMPARTILHAR: 0},
	{AnúncioMóvel: 0},
	{FonteDeSprites: 0},
	{FonteDeSprites2: 0},
	{SPRITE_CARREGANDO_JOGO: 0},
	{BTN_JOGAR: 0},
	{ganhoujogo: 0},
	{tamanho_sombra: 0},
	{v_MEDALHA3RNGAMES: 0},
	{v_medalha_ouro: 0},
	{v_medalha_prata: 0},
	{v_medalha_bronze: 0},
	{TRANSPARENCIA: 0},
	{volumesom: 0},
	{volume_ponto_de_salvamento: 0},
	{volume_medalha: 0},
	{volume_grama: 0},
	{volume_pular: 0},
	{escala: 0},
	{PONTOS: 0},
	{POSICAO_PERSONAGEM: 0},
	{VAR_PROGRESSO_CARREGAMENTO_IMAGEM: 0},
	{VAR_TODAS_ACOES_OBTER_ITEN_CONCLUIDAS: 0},
	{VAR_CARREGAMENTO_IMAGEM_COMPLETAR: 0},
	{assistiranunciovideo: 0},
	{velocidade: 0},
	{tamanho: 0},
	{parar: 0},
	{tempo: 0},
	{volume_musica: 0},
	{COR_VERMELHA: 0},
	{POSICAO_CORES: 0},
	{VELOCIDADE_SOMBRA: 0},
	{PAINEL_ATIVADO: 0}
];

self.InstanceType = {
	bg10: class extends self.ISpriteInstance {},
	bg12: class extends self.ISpriteInstance {},
	bg14: class extends self.ISpriteInstance {},
	bg2: class extends self.ISpriteInstance {},
	bg3: class extends self.ISpriteInstance {},
	bg4: class extends self.ISpriteInstance {},
	bg5: class extends self.ISpriteInstance {},
	bg7: class extends self.ISpriteInstance {},
	bg8: class extends self.ISpriteInstance {},
	bg9: class extends self.ISpriteInstance {},
	BG15: class extends self.ISpriteInstance {},
	bg1: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	BGTELA3: class extends self.ISpriteInstance {},
	FundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	bola: class extends self.ISpriteInstance {},
	SOMBRA: class extends self.ISpriteInstance {},
	animacaoraio: class extends self.ISpriteInstance {},
	grama: class extends self.ISpriteInstance {},
	nuvem: class extends self.ISpriteInstance {},
	nuvem_trovao: class extends self.ISpriteInstance {},
	tijolo1: class extends self.ISpriteInstance {},
	tijolo2: class extends self.ISpriteInstance {},
	tijolo_colorido: class extends self.ISpriteInstance {},
	tijolo_dourado: class extends self.ISpriteInstance {},
	TIJOLO_METAL: class extends self.ISpriteInstance {},
	ESTRELAS: class extends self.ISpriteInstance {},
	medalha_ouro: class extends self.ISpriteInstance {},
	medalha_bronze: class extends self.ISpriteInstance {},
	medalha_prata: class extends self.ISpriteInstance {},
	medalha3rngamesentretenimento: class extends self.ISpriteInstance {},
	obstaculo1: class extends self.ISpriteInstance {},
	obstaculo_prata: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles10: class extends self.IParticlesInstance {},
	Particles12: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles8: class extends self.IParticlesInstance {},
	Particles7: class extends self.IParticlesInstance {},
	particula: class extends self.IParticlesInstance {},
	Particles9: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Particles11: class extends self.IParticlesInstance {},
	Particles13: class extends self.IParticlesInstance {},
	pedramarromescuro: class extends self.ISpriteInstance {},
	predramarromclaro: class extends self.ISpriteInstance {},
	rocha: class extends self.ISpriteInstance {},
	Particles14: class extends self.IParticlesInstance {},
	Particles15: class extends self.IParticlesInstance {},
	Partículas: class extends self.IParticlesInstance {},
	particula_tijolo_metal: class extends self.IParticlesInstance {},
	PARTICULA_TIJOLO_COLORIDO: class extends self.IParticlesInstance {},
	PARTICULA_TIJOLO_DOURADO: class extends self.IParticlesInstance {},
	Particles16: class extends self.IParticlesInstance {},
	PREMIO_3RN_GAMES: class extends self.ISpriteInstance {},
	PREMIO_A: class extends self.ISpriteInstance {},
	PREMIO_N: class extends self.ISpriteInstance {},
	PREMIO_S: class extends self.ISpriteInstance {},
	PREMIO_R: class extends self.ISpriteInstance {},
	PREMIO_D: class extends self.ISpriteInstance {},
	afrodite: class extends self.ISpriteInstance {},
	pandora: class extends self.ISpriteInstance {},
	poseidom: class extends self.ISpriteInstance {},
	persefone: class extends self.ISpriteInstance {},
	zeus: class extends self.ISpriteInstance {},
	cronos: class extends self.ISpriteInstance {},
	PREMIO_OURO: class extends self.ISpriteInstance {},
	PREMIO_PRATA: class extends self.ISpriteInstance {},
	PREMIO_BRONZE: class extends self.ISpriteInstance {},
	premio3rngames: class extends self.ISpriteInstance {},
	playstore_3rngamesentretenimento: class extends self.ISpriteInstance {},
	TXTPULOS: class extends self.ISpriteInstance {},
	PLANODEFUNDO: class extends self.ISpriteInstance {},
	BTNJOGAR: class extends self.ISpriteInstance {},
	LOGO_3RN_GAMES_ENTRETENIMENTO: class extends self.ISpriteInstance {},
	SETA_DIREITA: class extends self.ISpriteInstance {},
	SETA_ESQUERDA: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	BTNANUNCIOVIDEO: class extends self.ISpriteInstance {},
	ANIMACAO: class extends self.ISpriteInstance {},
	btnganhoujogo: class extends self.ISpriteInstance {},
	seta_direita_desativado: class extends self.ISpriteInstance {},
	seta_esquerda_desativado: class extends self.ISpriteInstance {},
	btn_continuar_desativado: class extends self.ISpriteInstance {},
	btn_nao: class extends self.ISpriteInstance {},
	btn_novo_jogo: class extends self.ISpriteInstance {},
	btn_sim: class extends self.ISpriteInstance {},
	btncontinuar: class extends self.ISpriteInstance {},
	PAINEL_CERTEZA: class extends self.ISpriteInstance {},
	PAINEL_ORBITA: class extends self.ISpriteInstance {},
	poder_amarelo: class extends self.ISpriteInstance {},
	poder_azul: class extends self.ISpriteInstance {},
	poder_rosa: class extends self.ISpriteInstance {},
	poder_roxo: class extends self.ISpriteInstance {},
	poder_verde: class extends self.ISpriteInstance {},
	poder_vermelho: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	SETADIREITA: class extends self.ISpriteInstance {},
	SETAESQUERDA: class extends self.ISpriteInstance {},
	decmusic5: class extends self.ISpriteInstance {},
	decmusic10: class extends self.ISpriteInstance {},
	decmusic2: class extends self.ISpriteInstance {},
	decmusic4: class extends self.ISpriteInstance {},
	decmusic7: class extends self.ISpriteInstance {},
	decmusic8: class extends self.ISpriteInstance {},
	DEC_PONTOS: class extends self.ISpriteInstance {},
	setavoltarmenu: class extends self.ISpriteInstance {},
	texto1: class extends self.ISpriteInstance {},
	texto2: class extends self.ISpriteInstance {},
	texto3: class extends self.ISpriteInstance {},
	BTN_CONTINUAR: class extends self.ISpriteInstance {},
	BTN_MENU: class extends self.ISpriteInstance {},
	BTN_PAUSAR: class extends self.ISpriteInstance {},
	painel: class extends self.ISpriteInstance {},
	S1: class extends self.ISpriteInstance {},
	S2: class extends self.ISpriteInstance {},
	S3: class extends self.ISpriteInstance {},
	S4: class extends self.ISpriteInstance {},
	S5: class extends self.ISpriteInstance {},
	S6: class extends self.ISpriteInstance {},
	S7: class extends self.ISpriteInstance {},
	S8: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BarraDeProgresso: class extends self.IProgressBarInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Compartilhar: class extends self.IInstance {},
	BTN_COMPARTILHAR: class extends self.ISpriteInstance {},
	AnúncioMóvel: class extends self.IInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	SPRITE_CARREGANDO_JOGO: class extends self.ISpriteInstance {},
	BTN_JOGAR: class extends self.ISpriteInstance {}
}